version: '3'
services:
  web:
    image: httpd:latest
    ports:
      - 80:80
    volumes:
      - ./www:/usr/local/apache2/htdocs/
    networks:
      - mynetwork
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - 3306:3306
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge